---
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
language: ruby
bundler_args: --without development --without integration
script: "bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_GEM_VERSION=3.1.1
  - PUPPET_GEM_VERSION=3.2.4
  - PUPPET_GEM_VERSION=3.3.2
  - PUPPET_GEM_VERSION=3.4.3
  - PUPPET_GEM_VERSION=3.5.1
  - PUPPET_GEM_VERSION=3.6.2
  - PUPPET_GEM_VERSION=3.7.1
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION=3.1.1
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION=3.1.1
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION=3.2.4
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION=3.3.2
    - rvm: 2.1.2
      env: PUPPET_GEM_VERSION=3.1.1
    - rvm: 2.1.2
      env: PUPPET_GEM_VERSION=3.2.4
    - rvm: 2.1.2
      env: PUPPET_GEM_VERSION=3.3.2
notifications:
  email: false
